### ISSUE TITLE
Stylize landing page

### ISSUE THREAD

**Issue by VittaSil** [EECE3093C/team-project-rocket-frontend#29]
Change background colors of non-logged in landing page to be one of five main colors: white, blue, red, green, or dark purple. It should be a gradient that fades to black on the right side.

**Comment by jackbutler45** [comment]
Just for the non-logged in landing page or for everything?

**Comment by VittaSil** [comment]
Just for non-logged in page :+1:

**Comment by rajaware26** [comment]
Also try changing the gradient for the page
