### ISSUE TITLE
Create Left Nav menu on the dashboard

### ISSUE THREAD

**Issue by rajaware26** [EECE3093C/team-project-rocket-frontend#40]
Make a left nav menu for the user to access different tools - Deck, Cards, Trade, Wishlist

**Comment by VittaSil** [comment]
Left Nav Tabs in order:
- [ ] Cards  - basically homepage, dashboard user sees upon logging in.
- [ ] Decks  - similar to Cards, contains decks instead, organized lists of cards
- [ ] Sets  - where users can select cards to add to collection/wishlist; lists sets which can be expanded/filtered, or just raw search a card name
- [ ] Trade  - where users can see friends and initiate/manage trades
- [ ] Wishlist  - display of user's desired cards
- [ ] Friends  - list of user's added friends, user can manage
- [ ] Help  - tutorial vid, faq

**Comment by rajaware26** [comment]
I think you have covered all the tabs important in our left nav
