### ISSUE TITLE
Create card display area on dashboard

### ISSUE THREAD

**Issue by rajaware26** [EECE3093C/team-project-rocket-frontend#41]
Make a large area to display cards

**Comment by VittaSil** [comment]
Display a message for an empty display: "Welcome to CardStock! Get started on your collection _here_ or learn how to by watching this short _tutorial._"

The word "here" should link to the Sets tab. I may make a brief (two minute) tutorial video we can embed there. It will be under a Help tab as well.

**Comment by rajaware26** [comment]
Yeah the way it should work later is to show a user's card/cards when selected
